Error404
reservamos/frontend-playground pull request #16
Opened 2021-01-05 21:13 UTC by brendaorozcoreservamos

Ultimas correcciones de sintaxis

2021-01-05 22:30 UTC, perezjair commented
Viendo el screenshot creo que faltan pequeños ajustes de margenes y paddings para que el diseño se asemeje más al del mockup, un de los más notorios es el botón de regresar al inicio, creo que en ese botón hace falta reducir el padding

![image](https://user-images.githubusercontent.com/25155287/103706949-60468600-4f73-11eb-92d4-9de4bf9be496.png)

2021-01-06 00:19 UTC, angelfhuerta requested changes

2021-01-06 00:19 UTC, angelfhuerta commented on pages/error.js
> +      <div className="columnone">
En cuanto a los nombres de las clases, cuando tienen 2 o más palabras es mejor separarlas por un "-" en este caso sería `column-one`  esto ayuda a tener una mejor lectura de las clases y el código

2021-01-06 00:19 UTC, angelfhuerta commented on styles/components/styles.scss
> +  color: $accent-500;
Acá este estilo funciona, pero creo que cuando son estilos de fonts en específico es mejor usar el mixin de `font-styles` para definir en específico los estilos del font. En este caso sería algo así:

```
h1 {
  @include font-styles($accent-500, 35px, 700);
  padding: 15px 0;
}
```

Lo que se está definindo en el mixin son las propiedades de color, font-size y font-weight.

2021-01-06 00:19 UTC, angelfhuerta commented on styles/components/styles.scss
> +  line-height: 2em;
Acá el `line-height` está funcionando ahorita para darle espaciado a los elementos de la lista, pero creo que es mejor usar esta propiedad para darle espaciado al interlineado de un párrafo. Creo que para darle espacio a cada `li` es mejor usar un margin en los `li`

2021-01-06 00:19 UTC, angelfhuerta commented on styles/components/styles.scss
> + li:before { content: "• "; }
Si se quita el `line-height` del `ul` se le agregaría un `margin: 10px 0;`  al `li` quedaría algo así:

```
   li {
    padding: 10px 0;

    &:before {
      content: "• ";
    }
  }
```

2021-01-06 00:19 UTC, angelfhuerta commented on pages/error.js
> +      <div className="columntwo">
En esta columna creo que la estructura de los elementos queda mejor si separamos por bloques, es decir el primer bloque padre sería el `columntwo` y dentro de este div estarían otros dos bloques, puede ser `routes-links` , el html quedaría algo así:

```
      <div className="columntwo">
        <div className="links">
          <h3>Explora nuestras rutas en Mexico</h3>
          <div className="tags-item">
            <a>...</a>
            <a>...</a>
            <a>...</a>
            <a>...</a>
            <a>...</a>
            <a>...</a>
          </div>
        </div>
        <div className="links">
          <h3>Explora nuestras rutas en EUA</h3>
          <div className="tags-itemtwo">
            <a>...</a>
            <a>...</a>
            <a>...</a>
            <a>...</a>
            <a>...</a>
            <a>...</a>
          </div>
        </div>
      </div>
```

2021-01-06 00:19 UTC, angelfhuerta commented on pages/error.js
> +      <div className="columntwo">
Si se hace este cambio se tendrían que hacer dos cambios en el css para que esta estructura funcione:

1. Agregar un `flex-direction: column` en la clase `columntwo` 
2. Cambiar las propiedades del margin que tiene ahorita el `<h3>` a la clase `links`

2021-01-06 00:19 UTC, angelfhuerta commented on styles/components/styles.scss
> +.columntwo {
con el cambio de estrcutura en el html, faltaría agregarle a esta clase la propiedad:

`flex-direction: column;`

2021-01-06 00:19 UTC, angelfhuerta commented on styles/components/styles.scss
> +h3 {
Este se podría cambiar en lugar de ser para el `<h3>` puede ser para la clase `links`

2021-01-06 00:19 UTC, angelfhuerta commented on styles/components/styles.scss
> +h3 {
También estaría bien agregarle un margin bottom a este h3, con el cambio que comento arriba quedaría algo así:

```
.links {
  margin-top: 50px;

  h3 {
    margin-bottom: 20px;
  }
}
```

2021-01-06 00:19 UTC, angelfhuerta commented on styles/components/styles.scss
> +  margin: 15px 0;
Aquí creo que sería mejor darle un padding de `30px 0` para darle más espacio al título

2021-01-07 19:40 UTC, perezjair requested changes

2021-01-07 19:40 UTC, cadillacone commented on styles/components/error.scss
> +  margin: 7px;
Aquí creo que es mejor utilizar solo un margen del lado derecho y hacía abajo ya que al tener un margen izquierdo hace que el componente no se encuentre alineado con respecto al título

> ![image](https://user-images.githubusercontent.com/25155287/103927045-622d5800-50df-11eb-91f5-5910ea6a6d30.png)

Al establecer el margen derecho e inferior solo lo aplicamos en donde nos interesa que es para separar los links:
> ![image](https://user-images.githubusercontent.com/25155287/103927163-87ba6180-50df-11eb-9273-f3e67f9b59d3.png)

El valor sería de esta manera: 
```scss
margin: 0 10px 10px 0;
```

2021-01-07 19:40 UTC, cadillacone commented on styles/components/error.scss
> +  text-decoration: 0;
Aquí para resetear valores por default lo recomendable es poner el valor inicial de la propiedad, en este caso sería `none` en lugar de `0`

Cada propiedad tiene un valor inicial distinto, en esta página de w3schools existe toda la documentación
https://www.w3schools.com/cssref/pr_text_text-decoration.asp

2021-01-07 19:40 UTC, cadillacone commented on styles/components/error.scss
> +}
Estas propiedades que son las que dan estilos al botón es mejor dárselas directamente al elemento `<a>` en lugar del `<div>` que contiene el `<a>`

Adicionalmente agregaría la propiedad `display: block;` a los estilos del botón

Actualmente como está el botón solo se acciona dandole clic al texto
![image](https://user-images.githubusercontent.com/25155287/103930397-45475380-50e4-11eb-87a0-ad8de82060f5.png)

2021-01-07 19:40 UTC, cadillacone commented on styles/components/error.scss
> +.logo img {
Aquí hay que recordar que con Scss se pueden anidar clases utilizando `&`, para este caso puede quedar de esta manera:

```scss
.logo {
...

  & img {
    ...
  }
}
```

2021-01-07 19:40 UTC, cadillacone commented on pages/index.js
> +      <p className="example-text">Hello, Brenda!</p>
Esto lo podemos dejar como estaba anteriormente 😅

2021-01-07 19:40 UTC, cadillacone commented on styles/components/error.scss
> +  padding: 30px 0;
Aquí el padding cumple la función de separar la ilustración y el contenido de abajo con el título pero creo que esto es mejor usando un enfoque en el que se establezcan márgenes inferiores

---
> ![image](https://user-images.githubusercontent.com/25155287/103931233-99066c80-50e5-11eb-9666-f515fb4b081f.png)
---

Para que la ilustración y el título tengan su propio margen inferior ya que en dado caso que el título no estuviera se perdería el espaciado entre la ilustración y el contenido de abajo

---
> ![image](https://user-images.githubusercontent.com/25155287/103931320-bc311c00-50e5-11eb-9ec9-704a77e6ac19.png)
--- 

Aquí lo cambiaría por `margin-bottom: 30px;`

2021-01-07 19:40 UTC, cadillacone commented on styles/components/error.scss
> +  list-style-type: 0;
Aquí el valor inicial es `none` en el inspector cuando hay propiedades con valores no admitidos te marca un icono de warning ⚠️ 

![image](https://user-images.githubusercontent.com/25155287/103931805-7cb6ff80-50e6-11eb-99bd-891454be57ae.png)

2021-01-07 19:40 UTC, cadillacone commented on styles/components/error.scss
> +li {
Estas propiedades de `li` pueden estar dentro del `ul`

```scss
ul {
  ...
  
  li {
    ...

    &::before {
      ...
    }
  }
}
```

2021-01-07 19:40 UTC, cadillacone commented on styles/components/error.scss
> +  display: flex;
Aquí hay dos propiedades iguales

2021-01-07 19:40 UTC, cadillacone commented on styles/components/error.scss
> +  margin: 0 20 20 0;
A este margen le hace falta las unidades al `20px`, los únicos valores que no llevan unidades son los `0`

2021-01-07 19:40 UTC, cadillacone commented on styles/components/error.scss
> +  }
Este _hover_ tiene más sentido que vaya junto con los estilos del botón, en el selector `.column-two a` línea 112

2021-01-07 19:40 UTC, cadillacone commented on styles/components/error.scss
> +.tags-item-two {
Aquí creo que no hay diferencia entre la clase `.tags-item` y `.tags-item-two` así que creo que se pueden usar la misma clases en el JS

![image](https://user-images.githubusercontent.com/25155287/103932624-bc321b80-50e7-11eb-9581-6b35585e9671.png)

2021-01-07 19:40 UTC, perezjair commented on styles/components/error.scss
> +  grid-template-columns: 1fr 1fr;
Conforme a lo que hablamos ayer creo que el grid de la página puede quedar distribuido de la siguiente manera:
![image](https://user-images.githubusercontent.com/25155287/103935250-ef76a980-50eb-11eb-97ad-2d938d220b8f.png)

2021-01-07 19:40 UTC, perezjair commented on pages/error.js
> +        <div className="illust">
Aquí sería mejor que la clase se llamara `illustration` queda más claro, lo ideal es que el nombre de la clase te de cierto contexto y puedas ubicar fácilmente en la hoja de estilos

2021-01-07 19:40 UTC, perezjair commented on pages/error.js
> +        <div className="text-one">
Aquí a lo mejor un nombre más apropiado es algo como "description"

2021-01-07 19:40 UTC, perezjair commented on pages/error.js
> +          </div>
Aquí como comentaba en la parte del estilo, el botón puede quedar sin estar encerrado en el div y el mismo tener la clase

```jsx
<a className="button-one" href="https://www.reservamos.mx/" target="_blank" rel="noopener noreferrer">Regresar al inicio</a
```

2021-01-07 19:40 UTC, perezjair commented on pages/error.js
> +              <a className="tags-link" title="Destinos y rutas de autobús en México" href="#mexico">México</a>
Sobre el nombre de la clase creo que hay dos tipos de botones y estos pueden ser:
`button-primary`
![image](https://user-images.githubusercontent.com/25155287/103936340-e803d000-50ec-11eb-915e-a162fceb331c.png)

`button-secondary`
![image](https://user-images.githubusercontent.com/25155287/103936286-d8848700-50ec-11eb-99a1-40f95b57cb78.png)

2021-01-07 19:40 UTC, perezjair commented on pages/error.js
> +          </div>
También creo que este link puede quedar solo y con el nombre de clase `description-link` ya que no es un botón tal cual si no un link

2021-01-07 19:40 UTC, perezjair commented on pages/error.js
> +          </ul>
Aquí lo preferible es que en lugar de darle estilos a un elemento por medio de la etiqueta html lo demos por medio de las clases


```html
<h1 className="description-title">
<p className="description-paragraph">
<ul className="description-list">
```

2021-01-07 22:09 UTC, brendaorozcoreservamos commented on pages/error.js
> +          </div>
cuando quito el div ya no me agarra la propiedad de margin-top para el espaciado entre el button-primary y link
![Screen Shot 2021-01-07 at 4 07 48 PM](https://user-images.githubusercontent.com/75743401/103950543-ab42d380-5102-11eb-89ea-2ab2dadac8e9.png)

2021-01-07 22:27 UTC, perezjair commented on pages/error.js
> +          </div>
creo que es porqué al link le hace falta la propiedad `display: block`

2021-01-07 22:29 UTC, brendaorozcoreservamos commented on pages/error.js
> +          </div>
ya lo solucione, vi que solo faltaba un display: block;

2021-01-08 22:39 UTC, perezjair requested changes

2021-01-08 22:39 UTC, perezjair commented on pages/error.js
> +          <div className="button-secondary">
Aquí creo que hubo una confusión con el nombre de las clases, pero el que debería de tener la clase de `button-secondary` deberían de ser los links verdes, este div puede llamarse `routes-container` o `links-container`

2021-01-08 22:39 UTC, perezjair commented on pages/error.js
> +        </div>
Este div `<div className="links">` lo puedes quitar

Actualmente la estructura está así:
```html
<div class="links">
  <h3>
  <div class="rutas" />
  <div class="links">
    <h3>
    <div class="rutas" />
  </div>
</div>
```

Puede quedar de esta manera:
```html
<div class="links">
  <h3>
  <div class="rutas" />
  <h3>
  <div class="rutas" />
</div>
```

2021-01-08 22:39 UTC, perezjair commented on pages/error.js
> +          <div className="button-secondary-two">
Para este div se puede usar la misma clase que para el grupo de arriba, puede ser `routes-container` o `links-container` pero la misma puede funcionar para ambos

2021-01-08 22:39 UTC, perezjair commented on styles/components/error.scss
> +  margin: 0 20px 20px 0;
Aquí creo que es mejor solo establecer el margen inferior
`margin-bottom: 20px`

2021-01-08 22:39 UTC, perezjair commented on styles/components/error.scss
> +  }
En mobile me parece mejor que el contenido esté alineado a la izquierda en lugar de dejarlo centrado, creo que de esta manera se ve más ordenado todo, solo la ilustración la dejaría centrada 🤔  qué opinan?

`cambio - sugerido`
![image](https://user-images.githubusercontent.com/25155287/104071467-d8f54e80-51ce-11eb-8f0b-87980e6a06c9.png)

`actual - centrado`
![image](https://user-images.githubusercontent.com/25155287/104072011-e19a5480-51cf-11eb-8a07-a8d3792f030b.png)

2021-01-08 22:39 UTC, perezjair commented on styles/components/error.scss
> +.description-link {
Esto se puede meter en el bloque de css de `description`

2025-09-03 22:56 UTC, e3matheus commented
Cerrado automáticamente (criterio: created < 2025-06-03). Añade la etiqueta "keep-open" si debe permanecer abierto.

2025-09-03 22:56 UTC, closed without merging